### ISSUE TITLE
What is the correct way to enter --outdir?

### ISSUE THREAD

**Issue by kevinhuang61** [aronbrand/astriaclient#3]
python astriaclient/astria.py [--key] downloadall tuneid [--outdir]

I tried several --outdir options but it gives me unrecognized arguments such as...

astria.py: error: unrecognized arguments: --outdir ./28620/
astria.py: error: unrecognized arguments: --outdir /28620
astria.py: error: unrecognized arguments: --outdir 28620

**Comment by aronbrand** [comment]
The syntax above is incorrect, outdir is a global flag, so it should be used like this:

Use:
python astriaclient/astria.py --outdir <dir> downloadall [tuneid] 

If you type astria.ph -h you will see that the outdir flag precedes the command:

usage: astria.py [-h] [--key KEY] [--callback CALLBACK] [--debug]
                 [--outdir OUTDIR]
                 {gen,tune,list,listtune,info,download,downloadall} ...

Command line tool for Astria

positional arguments:
  {gen,tune,list,listtune,info,download,downloadall}
    gen                 Generate images for prompts
    tune                Create a new tune
    list                List all generated images for a tune
    listtune            List all tunes in the account
    info                Get details of prompt
    download            Download images of prompt
    downloadall         Download recent images

optional arguments:
  -h, --help            show this help message and exit
  --key KEY             Astria API token
  --callback CALLBACK
  --debug
  --outdir OUTDIR       Output directory for images

**Comment by kevinhuang61** [comment]
It works, thanks.

However, it is now downloading .bak .dat and .dir files outside the designated directory without using --db argument

**Comment by aronbrand** [comment]
bak, dat and dir belong to the database
outdir only controls the downloaded images, and not the database files.
The db argument controls the name of the database file (if db argument not specified, default = astriacache).
